= Breaking: Arcooda Parters with Barnstorm Games
:hp-tags: arcooda, news, barnstorm, pro_pinball

Arcooda hinted at exciting things to come today on their twitter account, so I asked them what they have in store for digital pinball fans.

As it turns out, Arcooda will officially confirm that they have entered into an official partnership with Barnstorm Games, makers of the acclaimed *Pro Pinball Ultra Edition* digital pinball brand.  

Many pinheads agree that Pro Pinball still contains the best ball physics and overall ruleset of any digital pinball simulation on the market today.
Now imagine hooking this simulation up with a fully-integrated digital pinball cabinet complete with DMD, backglass, real pinball components, full nudging support, and full touchscreen playfield. 

One word: *HUGE*

Arcooda has confirmed that _Timehock!: The Arcade Edition_ will also feature deep integration with both the Arcooda Video Pinball platform *and* Touch Wizard products.
From what I got from the scoop the team at Arcooda gave BlahCade, there is more to come with the platform as well including tournaments and other things you just can't get in the Steam version.

There are other things in the works that we can't share yet at BlahCade, but rest assured you'll hear them here first in our partnership with Arcooda. 

With Arcooda, it's _Game Never Over_.
What are your thoughts about this new deal? Has Arcooda got your attention yet? 